# Generated by Django 3.2 on 2022-01-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedular',
            name='academic_year_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Academic Year Code'),
        ),
        migrations.AlterField(
            model_name='schedular',
            name='associated_program_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Associated Program Code'),
        ),
    ]
