# Generated by Django 3.2 on 2022-01-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20220105_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedular',
            name='class_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial'), ('Lab', 'Lab')], max_length=255, verbose_name='Class Type'),
        ),
        migrations.AlterField(
            model_name='schedular',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255, verbose_name='Status'),
        ),
    ]
