# Generated by Django 3.2 on 2022-01-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_schedular_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedular',
            name='student_image',
        ),
    ]
